/* Generated By:JJTree: Do not edit this line. ASTADD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADD extends SimpleNode {
  private String op;
  
  public ASTADD(int id) {
    super(id);
  }

  public ASTADD(Project p, int id) {
    super(p, id);
  }

  public void setOp(String n) {
    op = n;
  }

  public String toString() {
    return "Operation: +";
  }

}
/* JavaCC - OriginalChecksum=799bc7a3e5b9cd5f2280cdeb76928da4 (do not edit this line) */
