/* Generated By:JJTree: Do not edit this line. ASTArray.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArray extends SimpleNode {
  public ASTArray(int id) {
    super(id);
  }

  public ASTArray(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=085efc60f46babf8e55f725b31473ce8 (do not edit this line) */
