/* Generated By:JJTree: Do not edit this line. ASTADD.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTADD extends SimpleNode {
  private String op;

  public ASTADD(int id) {
    super(id);
  }

  public ASTADD(Project p, int id) {
    super(p, id);
  }
  
  public void setOp(String n) {
    op = n;
  }

  public String toString() {
    op = "+";
    return "Operation: +";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f36730e62f7f0ee6a40aea353f2a8287 (do not edit this line) */
