/* Generated By:JJTree: Do not edit this line. ASTAccessingArrayAt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccessingArrayAt extends SimpleNode {
  public ASTAccessingArrayAt(int id) {
    super(id);
  }

  public ASTAccessingArrayAt(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1ab0edab4ec40e9ec19c811ebefd757 (do not edit this line) */
