/* Generated By:JJTree: Do not edit this line. ASTAcessing.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAcessing extends SimpleNode {
  public ASTAcessing(int id) {
    super(id);
  }

  public ASTAcessing(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=968e21f81973ed7f106075d3946c231f (do not edit this line) */
