/* Generated By:JJTree: Do not edit this line. ASTAND.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAND extends SimpleNode {
  private String op;
  
  public ASTAND(int id) {
    super(id);
  }

  public ASTAND(Project p, int id) {
    super(p, id);
  }

  public void setOp(String n) {
    op = n;
  }

  public String toString() {
    op = "&&";
    return "Operation: &&";
  }
}
/* JavaCC - OriginalChecksum=929ce467fe11903fb4e55cbb1598f979 (do not edit this line) */
