/* Generated By:JJTree: Do not edit this line. ASTArg.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArg extends SimpleNode {
  public ASTArg(int id) {
    super(id);
  }

  public ASTArg(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=23aecf72ed345b50c43fe042d5b44a34 (do not edit this line) */
