/* Generated By:JJTree: Do not edit this line. ASTAccessingArrayAt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAccessingArrayAt extends SimpleNode {
  public ASTAccessingArrayAt(int id) {
    super(id);
  }

  public ASTAccessingArrayAt(Project p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b8cf56129f940db2deee65514a801e33 (do not edit this line) */
