/* Generated By:JJTree: Do not edit this line. ASTBoolean.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBoolean extends SimpleNode {
  public ASTBoolean(int id) {
    super(id);
  }

  public ASTBoolean(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a9947e34df147baf49e03a2fb07fb45 (do not edit this line) */
