/* Generated By:JJTree: Do not edit this line. ASTBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBody extends SimpleNode {
  public ASTBody(int id) {
    super(id);
  }

  public ASTBody(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef555767e9ad7363471c10255574663f (do not edit this line) */
