/* Generated By:JJTree: Do not edit this line. ASTCondition.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCondition extends SimpleNode {
  public ASTCondition(int id) {
    super(id);
  }

  public ASTCondition(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f19c17c7118c6c6bb5ffe4c57005f54f (do not edit this line) */
