/* Generated By:JJTree: Do not edit this line. ASTCalling.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCalling extends SimpleNode {
  public ASTCalling(int id) {
    super(id);
  }

  public ASTCalling(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1e87614d798dea4fa3d31177751a760 (do not edit this line) */
