/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  private String name;
  
  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "ClassDeclaration: " + name;
  }

}
/* JavaCC - OriginalChecksum=fcee849262224e59ebed11bbc99d36a1 (do not edit this line) */
