/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  private String name;
  private String ext;

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }
  
  public String getName() {
    return name;
  }

  public void setExtends(String n) {
    ext = n;
  }

  public String getExtends() {
    return ext;
  }

  public String toString() {
    if(ext != null){
      return "ClassDeclaration: " + name + " | Extends: " + ext;
    }
    return "ClassDeclaration: " + name;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=54e9a5045ff4abf1794dc44af1aad946 (do not edit this line) */
