/* Generated By:JJTree: Do not edit this line. ASTExpressionAnd.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionAnd extends SimpleNode {
  private String op;

  public ASTExpressionAnd(int id) {
    super(id);
  }

  public ASTExpressionAnd(Project p, int id) {
    super(p, id);
  }

  public void setOp(String n) {
    op = n;
  }

  public String toString() {
    if(op == null)
      return "";
    return "Operation: " + op + "\n";
  }
}
/* JavaCC - OriginalChecksum=59cef15f18401c9b13c64d38486416d9 (do not edit this line) */
