/* Generated By:JJTree: Do not edit this line. ASTEQUAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQUAL extends SimpleNode {
  private String op;

  public ASTEQUAL(int id) {
    super(id);
  }

  public ASTEQUAL(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    op = "=";
    return "Assign: =";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=32a8aa2c2509cee945e7e152606fd78b (do not edit this line) */
