/* Generated By:JJTree: Do not edit this line. ASTExpressionRestOfClausesWoIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionRestOfClausesWoIdent extends SimpleNode {
  public ASTExpressionRestOfClausesWoIdent(int id) {
    super(id);
  }

  public ASTExpressionRestOfClausesWoIdent(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9f9cb76573e219b742d735f080861649 (do not edit this line) */
