/* Generated By:JJTree: Do not edit this line. ASTElseBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseBody extends SimpleNode {
  public ASTElseBody(int id) {
    super(id);
  }

  public ASTElseBody(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e9e6e46a35383a4def336fc10e80726 (do not edit this line) */
