/* Generated By:JJTree: Do not edit this line. ASTExpressionRestOfClausesWoIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionRestOfClausesWoIdent extends SimpleNode {
  public ASTExpressionRestOfClausesWoIdent(int id) {
    super(id);
  }

  public ASTExpressionRestOfClausesWoIdent(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "";
  }

}
/* JavaCC - OriginalChecksum=8d08246488e22a25b75f3867c006895c (do not edit this line) */
