/* Generated By:JJTree: Do not edit this line. ASTExpressionNew.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionNew extends SimpleNode {
  private String name;

  public ASTExpressionNew(int id) {
    super(id);
  }

  public ASTExpressionNew(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    if(name == null)
      return "";
    if(name.equals("int"))
      return "int array ";
    return "";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6c1c125fbfb85834ec3211e462c3de11 (do not edit this line) */
