/* Generated By:JJTree: Do not edit this line. ASTExpressionAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionAux extends SimpleNode {
  public ASTExpressionAux(int id) {
    super(id);
  }

  public ASTExpressionAux(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=170131418379720217133b34edbc7d6b (do not edit this line) */
