/* Generated By:JJTree: Do not edit this line. ASTExpressionMinorAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionMinorAux extends SimpleNode {
  private String name;
  
  public ASTExpressionMinorAux(int id) {
    super(id);
  }

  public ASTExpressionMinorAux(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    if(name == null)
      return "";
    return "Operation: " + name;
  }
}
/* JavaCC - OriginalChecksum=5c2afa931c1381ddad191dfc5f7f8399 (do not edit this line) */
