/* Generated By:JJTree: Do not edit this line. ASTEQUAL.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEQUAL extends SimpleNode {
  private String op;

  public ASTEQUAL(int id) {
    super(id);
  }

  public ASTEQUAL(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    op = "=";
    return "Assign: =";
  }
}
/* JavaCC - OriginalChecksum=04fd0291a05b85962f53cbbe14427669 (do not edit this line) */
