/* Generated By:JJTree: Do not edit this line. ASTExpressionMinor.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionMinor extends SimpleNode {
  public ASTExpressionMinor(int id) {
    super(id);
  }

  public ASTExpressionMinor(Project p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=128a70268a6be7e05d7233af2250defd (do not edit this line) */
