/* Generated By:JJTree: Do not edit this line. ASTElseBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElseBody extends SimpleNode {
  public ASTElseBody(int id) {
    super(id);
  }

  public ASTElseBody(Project p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fa02e94f07db04c9d3cbfce413f23345 (do not edit this line) */
