/* Generated By:JJTree: Do not edit this line. ASTExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression extends SimpleNode {
  private String op;
  
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(Project p, int id) {
    super(p, id);
  }

  public void setOp(String n) {
    op = n;
  }

  public String toString() {
    if(op == null)
      return "";
    return "Operation: " + op;
  }
}
/* JavaCC - OriginalChecksum=a17cf35d1d2d8f58c455de1787aed92a (do not edit this line) */
