/* Generated By:JJTree: Do not edit this line. ASTExpressionRestOfClauses.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionRestOfClauses extends SimpleNode {
  public ASTExpressionRestOfClauses(int id) {
    super(id);
  }

  public ASTExpressionRestOfClauses(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=605ae5ba3330e3947c5255ea9fc278d4 (do not edit this line) */
