/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdentifier extends SimpleNode {
  private String name;
  
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "Identifier: " + name;
  }

}
/* JavaCC - OriginalChecksum=2303515ad12d6892bc84e090df3589b2 (do not edit this line) */
