/* Generated By:JJTree: Do not edit this line. ASTIfElseStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfElseStatement extends SimpleNode {
  public ASTIfElseStatement(int id) {
    super(id);
  }

  public ASTIfElseStatement(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd8fdb289cefaec180d927011f363f80 (do not edit this line) */
