/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntegerLiteral extends SimpleNode {
  private String name;
  private int value;

  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "Integer Literal: " + name;
  }
}
/* JavaCC - OriginalChecksum=0e30c57416b634d965fb444985d35f79 (do not edit this line) */
