/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInt extends SimpleNode {
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=402ab93bbbfa5f091899294d6ccd8313 (do not edit this line) */
