/* Generated By:JJTree: Do not edit this line. ASTIndentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIndentifier extends SimpleNode {
  public ASTIndentifier(int id) {
    super(id);
  }

  public ASTIndentifier(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb056320938b5cd4a0caed451e422aeb (do not edit this line) */
