/* Generated By:JJTree: Do not edit this line. ASTIfBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfBody extends SimpleNode {
  public ASTIfBody(int id) {
    super(id);
  }

  public ASTIfBody(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e17bd8ca623cb1634dc4e15961016f05 (do not edit this line) */
