/* Generated By:JJTree: Do not edit this line. ASTInMethod.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInMethod extends SimpleNode {
  public ASTInMethod(int id) {
    super(id);
  }

  public ASTInMethod(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=32f9c054b360a733b4e70d62aff99b2f (do not edit this line) */
