/* Generated By:JJTree: Do not edit this line. ASTIsArray.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIsArray extends SimpleNode {
  public ASTIsArray(int id) {
    super(id);
  }

  public ASTIsArray(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "is array";
  }

}
/* JavaCC - OriginalChecksum=faf2725379f27f86d9f10beef308a596 (do not edit this line) */
