/* Generated By:JJTree: Do not edit this line. ASTIfElseStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfElseStatement extends SimpleNode {
  public ASTIfElseStatement(int id) {
    super(id);
  }

  public ASTIfElseStatement(Project p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8bb284362cdccc1027f9ebbe857fc4ac (do not edit this line) */
