/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodDeclaration extends SimpleNode {
  private String name;
  
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "MethodDeclaration: " + name + "()";
  }


}
/* JavaCC - OriginalChecksum=6eee5dcf9fd726ed37d2eb0469f4176c (do not edit this line) */
