import java.util.List;
import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTMethodArgs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodArgs extends SimpleNode {
  private List<String> args = new ArrayList<String>();
  
  public ASTMethodArgs(int id) {
    super(id);
  }

  public ASTMethodArgs(Project p, int id) {
    super(p, id);
  }

  public void pushArg(String n) {
    args.add(n);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a429dd168c8c33c50ee7bd275114c594 (do not edit this line) */
