/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends SimpleNode {
  private String name;
  
  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "MainDeclaration | Arguments: " + name;
  }

}
/* JavaCC - OriginalChecksum=2e000c90bc7662d39b34cdc430115222 (do not edit this line) */
