/* Generated By:JJTree: Do not edit this line. ASTMINOR.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMINOR extends SimpleNode {
  private String op;

  public ASTMINOR(int id) {
    super(id);
  }

  public ASTMINOR(Project p, int id) {
    super(p, id);
  }

  public void setOp(String n) {
    op = n;
  }

  public String toString() {
    op = "<";
    return "Operation: <";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2cdcb0a5fa4ef4f0234b567801e5987 (do not edit this line) */
