/* Generated By:JJTree: Do not edit this line. ASTMainMethodBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainMethodBody extends SimpleNode {
  public ASTMainMethodBody(int id) {
    super(id);
  }

  public ASTMainMethodBody(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Function Body";
  }

}
/* JavaCC - OriginalChecksum=66752e7eb4df65d262f86d859c1ce1f6 (do not edit this line) */
