import java.util.List;
import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodDeclaration extends SimpleNode {
  private String name;
  private List<String> args = new ArrayList<String>();
  
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public void pushArg(String n) {
    args.add(n);
  }

  public String toString() {
    String retArgs = "";
    for(int i = 0; i < args.size(); i++){
      if(i == 0){
        retArgs += (" " + args.get(i));
      }
      else
        retArgs += (", " + args.get(i));
    }
    return "MethodDeclaration: " + name + "() | Arguments:" + retArgs;
  }

}
/* JavaCC - OriginalChecksum=6eee5dcf9fd726ed37d2eb0469f4176c (do not edit this line) */
