/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends SimpleNode {
  private String name;
  
  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "MainDeclaration | Argument: " + name;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ccd4fbbddf9c6916049ab2d0c8e3887d (do not edit this line) */
