import java.util.List;
import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTMethodArgs.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodArgs extends SimpleNode {
  private List<String> args = new ArrayList<String>();
  
  public ASTMethodArgs(int id) {
    super(id);
  }

  public ASTMethodArgs(Project p, int id) {
    super(p, id);
  }

  
  public void pushArg(String n) {
    args.add(n);
  }
/*
  public String toString() {
    String retArgs = "";
    for(int i = 0; i < args.size(); i++){
      if(i == 0){
        retArgs += (" " + args.get(i));
      }
      else
        retArgs += (", " + args.get(i));
    }
    return "Arguments:" + retArgs;
  }
  */

}
/* JavaCC - OriginalChecksum=f6ff02c855679e674ba5f255aa472791 (do not edit this line) */
