/* Generated By:JJTree: Do not edit this line. ASTMainMethodBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainMethodBody extends SimpleNode {
  public ASTMainMethodBody(int id) {
    super(id);
  }

  public ASTMainMethodBody(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Function Body";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0cf05f5233438fcc6a7c1a66dc2f87c0 (do not edit this line) */
