/* Generated By:JJTree: Do not edit this line. ASTMainMethodDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainMethodDeclaration extends SimpleNode {
  public ASTMainMethodDeclaration(int id) {
    super(id);
  }

  public ASTMainMethodDeclaration(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=073afc9e27d94ec1f1858453dfa606f0 (do not edit this line) */
