/* Generated By:JJTree: Do not edit this line. ASTStatementAux2.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementAux2 extends SimpleNode {
  private String operation;
  private String name;

  public ASTStatementAux2(int id) {
    super(id);
  }

  public ASTStatementAux2(Project p, int id) {
    super(p, id);
  }

  public void setOperation(String n) {
    operation = n;
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    if(name != null){
      return "Identifier: " + name;
    }
    if(operation == null)
      return "";
    if(operation.equals("=")){
      return "Assign: =";
    }
    else if(operation.equals(".")){
      return "Method: ";
    }
    else if(operation.equals("[")){
      return "Accessing array at:";
    }
    return "ERROR STATEMENT!";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73f7679d8bc81ae09c4f6ef4b2cf288d (do not edit this line) */
