/* Generated By:JJTree: Do not edit this line. ASTStatementAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementAux extends SimpleNode {
  public ASTStatementAux(int id) {
    super(id);
  }

  public ASTStatementAux(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f652cd7fd76ef419409ff1d26a6cb570 (do not edit this line) */
