/* Generated By:JJTree: Do not edit this line. ASTStatementAux1.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementAux1 extends SimpleNode {
  private String operation;

  public ASTStatementAux1(int id) {
    super(id);
  }

  public ASTStatementAux1(Project p, int id) {
    super(p, id);
  }

  public void setOperation(String n) {
    operation = n;
  }
  
  public String toString() {
    if(operation==null)
      return "";
    if(operation.equals("="))
      return "Assign: =";
    return "";
  }
}
/* JavaCC - OriginalChecksum=9fe569642417be105d32251420d80ede (do not edit this line) */
