/* Generated By:JJTree: Do not edit this line. ASTStatVarDefi.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatVarDefi extends SimpleNode {
  public ASTStatVarDefi(int id) {
    super(id);
  }

  public ASTStatVarDefi(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f19764c6bd56200cc42f95507919008 (do not edit this line) */
