/* Generated By:JJTree: Do not edit this line. ASTStatementStartIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementStartIdent extends SimpleNode {
  private String first;
  private String type;
  
  public ASTStatementStartIdent(int id) {
    super(id);
  }

  public ASTStatementStartIdent(Project p, int id) {
    super(p, id);
  }

  public String get_type() {
    return this.type;
  }

  public void isVarDecl(String n) {
    first = n;
    if(first.equals(".") || first.equals("=") || first.equals(";"))
      type = "Statement";
    else 
      type = "VarDeclaration";
  }

  public String toString() {
    if(first.equals(".") || first.equals("=") || first.equals(";")){
      return "Statement ";
    }
    return "VarDeclaration ";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b3d2705f03b77fda38ea90685a0b13f2 (do not edit this line) */
