/* Generated By:JJTree: Do not edit this line. ASTStatementAux3.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatementAux3 extends SimpleNode {
  private String operation;
  private String name;

  public ASTStatementAux3(int id) {
    super(id);
  }

  public ASTStatementAux3(Project p, int id) {
    super(p, id);
  }

  public void setOperation(String n) {
    operation = n;
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    if(name != null){
      return "Identifier: " + name;
    }
    if(operation == null)
      return "";
    if(operation.equals("=")){
      return "Assign: =";
    }
    else if(operation.equals(".")){
      return "Method: ";
    }
    else if(operation.equals("[")){
      return "Accessing array at:";
    }
    return "ERROR STATEMENT!";
  }

}
/* JavaCC - OriginalChecksum=e6aabd081fea4e47cbd32fd674a88f01 (do not edit this line) */
