/* Generated By:JJTree: Do not edit this line. ASTStatVarDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatVarDecl extends SimpleNode {
  public ASTStatVarDecl(int id) {
    super(id);
  }

  public ASTStatVarDecl(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "Statement ";
  }


}
/* JavaCC - OriginalChecksum=94f6f8b1c7837c22735a64ed7b313b03 (do not edit this line) */
