/* Generated By:JJTree: Do not edit this line. ASTTypeWoIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeWoIdent extends SimpleNode {
  private String name;

  public ASTTypeWoIdent(int id) {
    super(id);
  }

  public ASTTypeWoIdent(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String getName() {
    return name;
  }
  
  public String toString() {
    return "Type: " + name;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ba4e332fd859c4de43d76c0c155f4bd (do not edit this line) */
