/* Generated By:JJTree: Do not edit this line. ASTTypeAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeAux extends SimpleNode {
  private String name;

  public ASTTypeAux(int id) {
    super(id);
  }

  public ASTTypeAux(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "Array";
  }

}
/* JavaCC - OriginalChecksum=cbd5eb3c91500879969d0d5ab312ea64 (do not edit this line) */
