/* Generated By:JJTree: Do not edit this line. ASTTypeWoIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTypeWoIdent extends SimpleNode {
  public ASTTypeWoIdent(int id) {
    super(id);
  }

  public ASTTypeWoIdent(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85c05f82394905aa7111aa7ee58cd4ba (do not edit this line) */
