/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDecl extends SimpleNode {
  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f34d29e8b8ca81b970e3a72199dec03a (do not edit this line) */
