/* Generated By:JJTree: Do not edit this line. ASTVarDeclarationWoIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclarationWoIdent extends SimpleNode {
  public ASTVarDeclarationWoIdent(int id) {
    super(id);
  }

  public ASTVarDeclarationWoIdent(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "VarDeclaration ";
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ca820e40ce883f3c78798c04ca04f34 (do not edit this line) */
