/* Generated By:JJTree: Do not edit this line. ASTVarDeclarationWoIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclarationWoIdent extends SimpleNode {
  private String name;
  
  public ASTVarDeclarationWoIdent(int id) {
    super(id);
  }

  public ASTVarDeclarationWoIdent(Project p, int id) {
    super(p, id);
  }

  public void setName(String n) {
    name = n;
  }

  public String toString() {
    return "VarDeclaration: " + name;
  }

}
/* JavaCC - OriginalChecksum=42aed206e06c4b5bad09ebd7c5940ee5 (do not edit this line) */
