/* Generated By:JJTree: Do not edit this line. ASTvoid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4591f11ea451fe8222dfcab20a60d792 (do not edit this line) */
