/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclaration extends SimpleNode {
  
  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(Project p, int id) {
    super(p, id);
  }

  public String toString() {
    return "VarDeclaration ";
  }
  

}
/* JavaCC - OriginalChecksum=cc87660a8ce3868dc08e5bb551e07e7b (do not edit this line) */
