/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Project p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ProjectVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e56445c59f58ab7afec367b03dacd0f (do not edit this line) */
