/* Generated By:JJTree: Do not edit this line. ASTWhileBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhileBody extends SimpleNode {
  public ASTWhileBody(int id) {
    super(id);
  }

  public ASTWhileBody(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d77fc33f3a8ca380f5ff8263572857a8 (do not edit this line) */
