/* Generated By:JavaCC: Do not edit this line. ProjectTreeConstants.java Version 6.0_1 */
public interface ProjectTreeConstants
{
  public int JJTVOID = 0;
  public int JJTINTEGERLITERAL = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTPROGRAM = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTVARDECLARATIONWOIDENT = 6;
  public int JJTMAINDECLARATION = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTISARRAY = 9;
  public int JJTSTATEMENTAUX2 = 10;
  public int JJTEXPRESSIONWOIDENT = 11;
  public int JJTEXPRESSIONTOKENWOIDENT = 12;
  public int JJTEXPRESSION = 13;
  public int JJTEXPRESSIONAND = 14;
  public int JJTEXPRESSIONMINOR = 15;
  public int JJTEXPRESSIONMINORAUX = 16;
  public int JJTEXPRESSIONADD = 17;
  public int JJTEXPRESSIONADDAUX = 18;
  public int JJTEXPRESSIONMULT = 19;
  public int JJTEXPRESSIONMULTAUX = 20;
  public int JJTEXPRESSIONRESTOFCLAUSES = 21;
  public int JJTEXPRESSIONAUX = 22;
  public int JJTEXPRESSIONAUXDOT = 23;
  public int JJTEXPRESSIONTOKEN = 24;
  public int JJTEXPRESSIONNEW = 25;


  public String[] jjtNodeName = {
    "void",
    "IntegerLiteral",
    "Identifier",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "VarDeclarationWoIdent",
    "MainDeclaration",
    "MethodDeclaration",
    "IsArray",
    "StatementAux2",
    "ExpressionWoIdent",
    "ExpressionTokenWoIdent",
    "Expression",
    "ExpressionAnd",
    "ExpressionMinor",
    "ExpressionMinorAux",
    "ExpressionAdd",
    "ExpressionAddAux",
    "ExpressionMult",
    "ExpressionMultAux",
    "ExpressionRestOfClauses",
    "ExpressionAux",
    "ExpressionAuxDot",
    "ExpressionToken",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=4fa491ec8da3582c90db3fc3cdc2ba5c (do not edit this line) */
