/* Generated By:JavaCC: Do not edit this line. ProjectTreeConstants.java Version 6.0_1 */
public interface ProjectTreeConstants
{
  public int JJTVOID = 0;
  public int JJTINTEGERLITERAL = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTPROGRAM = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTVARDECLARATIONWOIDENT = 6;
  public int JJTMAINDECLARATION = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTRETURN = 9;
  public int JJTMETHODARGS = 10;
  public int JJTARGUMENT = 11;
  public int JJTMAINMETHODBODY = 12;
  public int JJTTYPE = 13;
  public int JJTISARRAY = 14;
  public int JJTTYPEWOIDENT = 15;
  public int JJTCONDITION = 16;
  public int JJTIFBODY = 17;
  public int JJTELSEBODY = 18;
  public int JJTIFELSESTATEMENT = 19;
  public int JJTWHILEBODY = 20;
  public int JJTWHILESTATEMENT = 21;
  public int JJTSTATEMENTSTARTIDENT = 22;
  public int JJTAND = 23;
  public int JJTMINOR = 24;
  public int JJTADD = 25;
  public int JJTSUB = 26;
  public int JJTMULT = 27;
  public int JJTDIV = 28;
  public int JJTEQUAL = 29;
  public int JJTSTATEMENTAUX2 = 30;
  public int JJTCALLING = 31;
  public int JJTACESSING = 32;
  public int JJTINDEX = 33;
  public int JJTEXPRESSIONAUXDOT = 34;
  public int JJTEXPRESSIONTOKEN = 35;
  public int JJTEXPRESSIONTOKENWOIDENT = 36;
  public int JJTEXPRESSIONNEW = 37;


  public String[] jjtNodeName = {
    "void",
    "IntegerLiteral",
    "Identifier",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "VarDeclarationWoIdent",
    "MainDeclaration",
    "MethodDeclaration",
    "Return",
    "MethodArgs",
    "Argument",
    "MainMethodBody",
    "Type",
    "IsArray",
    "TypeWoIdent",
    "Condition",
    "IfBody",
    "ElseBody",
    "IfElseStatement",
    "WhileBody",
    "WhileStatement",
    "StatementStartIdent",
    "AND",
    "MINOR",
    "ADD",
    "SUB",
    "MULT",
    "DIV",
    "EQUAL",
    "StatementAux2",
    "Calling",
    "Acessing",
    "Index",
    "ExpressionAuxDot",
    "ExpressionToken",
    "ExpressionTokenWoIdent",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=7fb818cda24306e1219ce8b05dc3a52c (do not edit this line) */
