/* Generated By:JavaCC: Do not edit this line. ProjectTreeConstants.java Version 6.0_1 */
public interface ProjectTreeConstants
{
  public int JJTVOID = 0;
  public int JJTINTEGERLITERAL = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTPROGRAM = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTVARDECLARATIONWOIDENT = 6;
  public int JJTMAINDECLARATION = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTISARRAY = 9;
  public int JJTIFELSESTATEMENT = 10;
  public int JJTWHILESTATEMENT = 11;
  public int JJTSTATEMENTAUX1 = 12;
  public int JJTSTATEMENTAUX2 = 13;
  public int JJTAND = 14;
  public int JJTMINOR = 15;
  public int JJTADD = 16;
  public int JJTSUB = 17;
  public int JJTMULT = 18;
  public int JJTDIV = 19;
  public int JJTEXPRESSIONAUXDOT = 20;
  public int JJTEXPRESSIONTOKEN = 21;
  public int JJTEXPRESSIONTOKENWOIDENT = 22;
  public int JJTEXPRESSIONNEW = 23;


  public String[] jjtNodeName = {
    "void",
    "IntegerLiteral",
    "Identifier",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "VarDeclarationWoIdent",
    "MainDeclaration",
    "MethodDeclaration",
    "IsArray",
    "IfElseStatement",
    "WhileStatement",
    "StatementAux1",
    "StatementAux2",
    "AND",
    "MINOR",
    "ADD",
    "SUB",
    "MULT",
    "DIV",
    "ExpressionAuxDot",
    "ExpressionToken",
    "ExpressionTokenWoIdent",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=fcc424c6599b45423396eb15f75a0aac (do not edit this line) */
