/* Generated By:JavaCC: Do not edit this line. ProjectDefaultVisitor.java Version 6.0_1 */
public class ProjectDefaultVisitor implements ProjectVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIntegerLiteral node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIdentifier node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTProgram node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTClassDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVarDeclarationWoIdent node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMainDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMethodDeclaration node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMethodArgs node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTArgument node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMainMethodBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTType node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIsArray node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTypeWoIdent node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCondition node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTElseBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIfElseStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileStatement node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhileBody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatementStartIdent node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAND node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMINOR node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTADD node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSUB node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMULT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDIV node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTEQUAL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStatementAux2 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCalling node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpressionRestOfClauses node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpressionRestOfClausesWoIdent node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAcessing node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAccessingArrayAt node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpressionAuxDot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpressionToken node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpressionTokenWoIdent node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpressionNew node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=6ef3ab10d7d383f95ebc3c50a745b892 (do not edit this line) */
