/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 6.0_1 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;
  public int JJTVARDECL = 4;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
    "VarDecl",
  };
}
/* JavaCC - OriginalChecksum=534c1ba31eef53ff6096bf7e00c8ac50 (do not edit this line) */
