/* Generated By:JJTree: Do not edit this line. ASTExpressionWoIdent.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionWoIdent extends SimpleNode {
  public ASTExpressionWoIdent(int id) {
    super(id);
  }

  public ASTExpressionWoIdent(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89dcccbdbae3012e837dd3c63f8bf318 (do not edit this line) */
