/* Generated By:JJTree: Do not edit this line. ASTExpressionToken.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionToken extends SimpleNode {
  public ASTExpressionToken(int id) {
    super(id);
  }

  public ASTExpressionToken(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3acc0df314cdda7f1d72bebc9d08c6c (do not edit this line) */
