/* Generated By:JJTree: Do not edit this line. ASTExpressionAddAux.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionAddAux extends SimpleNode {
  public ASTExpressionAddAux(int id) {
    super(id);
  }

  public ASTExpressionAddAux(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a96d9500bc52c0937a2f4904c5e029a (do not edit this line) */
