/* Generated By:JJTree: Do not edit this line. ASTExpressionRestOfClauses.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionRestOfClauses extends SimpleNode {
  public ASTExpressionRestOfClauses(int id) {
    super(id);
  }

  public ASTExpressionRestOfClauses(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84aec4c622fde83f025b8b7d39d58d13 (do not edit this line) */
