/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntegerLiteral extends SimpleNode {
  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(Project p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e30c57416b634d965fb444985d35f79 (do not edit this line) */
