/* Generated By:JavaCC: Do not edit this line. ProjectTreeConstants.java Version 6.0_1 */
public interface ProjectTreeConstants
{
  public int JJTVOID = 0;
  public int JJTINTEGERLITERAL = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTPROGRAM = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTVARDECLARATIONWOIDENT = 6;
  public int JJTMAINDECLARATION = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTBODY = 9;
  public int JJTINMETHOD = 10;
  public int JJTISARRAY = 11;
  public int JJTSTATEMENT = 12;
  public int JJTSTATEMENTAUX = 13;
  public int JJTSTATEMENTAUX2 = 14;
  public int JJTEXPRESSIONWOIDENT = 15;
  public int JJTEXPRESSIONTOKENWOIDENT = 16;
  public int JJTEXPRESSION = 17;
  public int JJTEXPRESSIONAND = 18;
  public int JJTEXPRESSIONMINOR = 19;
  public int JJTEXPRESSIONMINORAUX = 20;
  public int JJTEXPRESSIONADD = 21;
  public int JJTEXPRESSIONADDAUX = 22;
  public int JJTEXPRESSIONMULT = 23;
  public int JJTEXPRESSIONMULTAUX = 24;
  public int JJTEXPRESSIONRESTOFCLAUSES = 25;
  public int JJTEXPRESSIONAUX = 26;
  public int JJTEXPRESSIONAUXDOT = 27;
  public int JJTEXPRESSIONTOKEN = 28;
  public int JJTEXPRESSIONNEW = 29;


  public String[] jjtNodeName = {
    "void",
    "IntegerLiteral",
    "Identifier",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "VarDeclarationWoIdent",
    "MainDeclaration",
    "MethodDeclaration",
    "Body",
    "InMethod",
    "IsArray",
    "Statement",
    "StatementAux",
    "StatementAux2",
    "ExpressionWoIdent",
    "ExpressionTokenWoIdent",
    "Expression",
    "ExpressionAnd",
    "ExpressionMinor",
    "ExpressionMinorAux",
    "ExpressionAdd",
    "ExpressionAddAux",
    "ExpressionMult",
    "ExpressionMultAux",
    "ExpressionRestOfClauses",
    "ExpressionAux",
    "ExpressionAuxDot",
    "ExpressionToken",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=69aae018787885cd82d427fe40a87b59 (do not edit this line) */
