/* Generated By:JavaCC: Do not edit this line. ProjectTreeConstants.java Version 6.0_1 */
public interface ProjectTreeConstants
{
  public int JJTEMPTY = 0;
  public int JJTINTEGERLITERAL = 1;
  public int JJTPROGRAM = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMAINMETHODDECLARATION = 5;
  public int JJTMAINDECLARATION = 6;
  public int JJTMETHODDECLARATION = 7;
  public int JJTTYPE = 8;
  public int JJTTYPEAUX = 9;
  public int JJTSTATEMENT = 10;
  public int JJTEXPRESSION = 11;
  public int JJTEXPRESSIONAUX = 12;
  public int JJTEXPRESSIONAUXDOT = 13;
  public int JJTEXPRESSIONAUXOPTIONAL = 14;
  public int JJTEXPRESSIONAUXASTERISK = 15;
  public int JJTEXPRESSIONTOKEN = 16;
  public int JJTEXPRESSIONNEW = 17;


  public String[] jjtNodeName = {
    "Empty",
    "IntegerLiteral",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainMethodDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Type",
    "TypeAux",
    "Statement",
    "Expression",
    "ExpressionAux",
    "ExpressionAuxDot",
    "ExpressionAuxOptional",
    "ExpressionAuxAsterisk",
    "ExpressionToken",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=9104c43fc3ad5ca92f41831a289d316b (do not edit this line) */
