/* Generated By:JavaCC: Do not edit this line. ProjectTreeConstants.java Version 6.0_1 */
public interface ProjectTreeConstants
{
  public int JJTEMPTY = 0;
  public int JJTINTEGERLITERAL = 1;
  public int JJTPROGRAM = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMAINMETHODDECLARATION = 5;
  public int JJTMAINDECLARATION = 6;
  public int JJTMETHODDECLARATION = 7;
  public int JJTTYPE = 8;
  public int JJTTYPEAUX = 9;
  public int JJTINMETHOD = 10;
  public int JJTSTATEMENT = 11;
  public int JJTSTATEMENTAUX = 12;
  public int JJTEXPRESSIONWOIDENT = 13;
  public int JJTEXPRESSIONTOKENWOIDENT = 14;
  public int JJTEXPRESSION = 15;
  public int JJTEXPRESSIONAUX = 16;
  public int JJTEXPRESSIONAUXDOT = 17;
  public int JJTEXPRESSIONTOKEN = 18;
  public int JJTEXPRESSIONNEW = 19;


  public String[] jjtNodeName = {
    "Empty",
    "IntegerLiteral",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainMethodDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Type",
    "TypeAux",
    "InMethod",
    "Statement",
    "StatementAux",
    "ExpressionWoIdent",
    "ExpressionTokenWoIdent",
    "Expression",
    "ExpressionAux",
    "ExpressionAuxDot",
    "ExpressionToken",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=77ef2f4ef4ea519b0cf7d6c669112ea3 (do not edit this line) */
