/* Generated By:JavaCC: Do not edit this line. ProjectTreeConstants.java Version 6.0_1 */
public interface ProjectTreeConstants
{
  public int JJTEMPTY = 0;
  public int JJTINTEGERLITERAL = 1;
  public int JJTPROGRAM = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMAINMETHODDECLARATION = 5;
  public int JJTMAINDECLARATION = 6;
  public int JJTMETHODDECLARATION = 7;
  public int JJTTYPE = 8;
  public int JJTTYPEAUX = 9;
  public int JJTSTATEMENT = 10;
  public int JJTEXPRESSION = 11;
  public int JJTEXPRESSIONAUX = 12;
  public int JJTEXPRESSIONTOKEN = 13;
  public int JJTEXPRESSIONNEW = 14;


  public String[] jjtNodeName = {
    "Empty",
    "IntegerLiteral",
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainMethodDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Type",
    "TypeAux",
    "Statement",
    "Expression",
    "ExpressionAux",
    "ExpressionToken",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=7b92a70440107c4b29d7a322253579b5 (do not edit this line) */
